export const categories = [
  {
    name: "Personal",
    keys: [
      { description: "Year of Birth" },
      { description: "Age" },
      { description: "Nationality" },
      { description: "Team/Squad" },
      { description: "Position" },
      { description: "Competition" },
    ],
  },
  {
    name: "Playing Time",
    keys: [
      { description: "Matches Played" },
      { description: "Minutes Played" },
      { description: "Percentage of Team Minutes Played" },
      { description: "Games Started" },
      { description: "Substitute Appearances" },
      { description: "Minutes per Match" },
      { description: "Minutes per Start" },
      { description: "Minutes per Substitute Appearance" },
      { description: "Unused Substitute" },
      { description: "Times Substituted In" },
      { description: "Times Substituted Out" },
    ],
  },
  {
    name: "Team Results",
    keys: [
      { description: "Wins" },
      { description: "Losses" },
      { description: "Team Goal Difference On/Off Pitch" },
      { description: "Points Per Match" },
    ],
  },
  {
    name: "Goals & Scoring",
    keys: [
      { description: "Goals" },
      { description: "Goals minus Penalties" },
      { description: "Goals minus Expected Goals" },
      { description: "Goals per Shot" },
      { description: "Goals per Shot on Target" },
      { description: "Goals plus Assists" },
      { description: "Goals plus Assists minus Penalties" },
      { description: "Own Goals" },
      { description: "Expected Goals" },
      { description: "Non-penalty Expected Goals" },
      { description: "Non-penalty xG plus Expected Assisted Goals" },
      { description: "Non-penalty xG per Shot" },
      { description: "xG plus xAG" },
      { description: "xG Plus/Minus" },
      { description: "xG Plus/Minus per 90" },
      { description: "Non-penalty Goals minus xG" },
    ],
  },
  {
    name: "Assists & Creation",
    keys: [
      { description: "Assists" },
      { description: "Expected Assists" },
      { description: "Expected Assisted Goals" },
      { description: "Key Passes" },
      { description: "Shot Creating Actions" },
      { description: "SCA per 90" },
      { description: "Goal Creating Actions" },
      { description: "GCA per 90" },
    ],
  },
  {
    name: "Shooting",
    keys: [
      { description: "Shots" },
      { description: "Shots on Target" },
      { description: "Shots on Target Percentage" },
      { description: "Shots per 90" },
      { description: "Shots on Target per 90" },
      { description: "Average Shot Distance" },
    ],
  },
  {
    name: "Passing",
    keys: [
      { description: "Passes Completed" },
      { description: "Pass Completion Percentage" },
      { description: "Passes Attempted" },
      { description: "Live Ball Passes" },
      { description: "Dead Ball Passes" },
      { description: "Assists" },
      { description: "Through Balls" },
      { description: "Key Passes" },
      { description: "Passes into Penalty Area" },
      { description: "Crosses" },
      { description: "Crosses into Penalty Area" },
      { description: "Average Pass Distance" },
      { description: "Average Pass Length" },
      { description: "Long Ball Percentage" },
      { description: "Switches" },
      { description: "Throw-Ins" },
      { description: "Turnovers" },
      { description: "Dead Ball Passes" },
      { description: "Live Ball Passes" },
    ],
  },
  {
    name: "Dribbling & Carrying",
    keys: [
      { description: "Carries" },
      { description: "Progressive Carries" },
      { description: "Progressive Carry Distance" },
      { description: "Progressive Runs" },
      { description: "Miscontrols" },
      { description: "Dispossessed" },
      { description: "Dribbles Attempted" },
      { description: "Successful Dribbles" },
      { description: "Dribble Success Percentage" },
      { description: "Dribbles in Attacking Third" },
      { description: "Dribbles in Penalty Area" },
    ],
  },
  {
    name: "Defending",
    keys: [
      { description: "Tackles" },
      { description: "Tackles Won" },
      { description: "Tackles plus Interceptions" },
      { description: "Tackle Success Percentage" },
      { description: "Interceptions" },
      { description: "Blocks" },
      { description: "Clearances" },
      { description: "Errors" },
      { description: "Defensive Actions" },
      { description: "Defensive Third" },
      { description: "Defensive Penalty Area" },
      { description: "Possession Lost" },
      { description: "Duels Won" },
      { description: "Duels Won Percentage" },
      { description: "Fouls Drawn" },
      { description: "Fouls Committed" },
      { description: "Yellow Cards" },
      { description: "Red Cards" },
      { description: "Second Yellow Cards" },
      { description: "Penalties Won" },
      { description: "Penalties Conceded" },
    ],
  },
  {
    name: "Goalkeeping",
    keys: [
      { description: "Clean Sheets" },
      { description: "Clean Sheet Percentage" },
      { description: "Saves" },
      { description: "Save Percentage" },
      { description: "Goals Against" },
      { description: "Goals Against per 90" },
      { description: "Shots on Target Against" },
      { description: "Post-Shot Expected Goals" },
      { description: "PSxG per Shot on Target" },
      { description: "PSxG Plus/Minus" },
      { description: "Penalties Against" },
      { description: "Penalty Saves" },
      { description: "Penalty Attempts" },
      { description: "Penalty Misses" },
    ],
  },
  {
    name: "Other/Advanced",
    keys: [
      { description: "Competitions Played" },
      { description: "Subbed Out" },
      { description: "Subbed In" },
      { description: "Passes Received" },
      { description: "Recoveries" },
      { description: "Touches" },
      { description: "Total Distance" },
      { description: "On-field xG" },
      { description: "On-field xGA" },
      { description: "On-field Goals" },
      { description: "On-field Goals Against" },
      { description: "Plus/Minus" },
      { description: "Plus/Minus per 90" },
      { description: "Offensive Possession Added" },
      { description: "OPA per 90" },
      { description: "Per 90" },
      { description: "Defensive Actions" },
      { description: "Opponents" },
      { description: "Stops" },
      { description: "Stop Percentage" },
      { description: "Throws" },
      { description: "Free Kicks" },
      { description: "Corner Kicks" },
      { description: "Completed Passes Attempted" },
      { description: "Average Length" },
      { description: "Switches" },
      { description: "Throw-Ins" },
      { description: "Turnovers" },
      { description: "Live Ball" },
      { description: "Dead Ball" },
    ],
  },
];