export const categories = [
  {
    name: "Personal",
    keys: [
      { description: "Year of Birth" },
      { description: "Age" },
      { description: "Nationality" },
      { description: "Team/Squad" },
      { description: "Position" },
      { description: "Competition" },
    ],
  },
  {
    name: "Playing Time",
    keys: [
      { description: "Matches Played" },
      { description: "Minutes Played" },
      { description: "Percentage of Team Minutes Played" },
      { description: "Games Started" },
      { description: "Substitute Appearances" },
      { description: "Minutes per Match" },
      { description: "Minutes per Start" },
      { description: "Minutes per Substitute Appearance" },
      { description: "Unused Substitute" },
      { description: "Times Substituted In" },
      { description: "Times Substituted Out" },
    ],
  },
  {
    name: "Team Results",
    keys: [
      { description: "Wins" },
      { description: "Losses" },
      { description: "Team Goal Difference On/Off Pitch" },
      { description: "Points Per Match" },
    ],
  },
  {
    name: "Goals & Scoring",
    keys: [
      { description: "Goals" },
      { description: "Goals minus Penalties" },
      { description: "Goals minus Expected Goals" },
      { description: "Goals per Shot" },
      { description: "Goals per Shot on Target" },
      { description: "Goals plus Assists" },
      { description: "Goals plus Assists minus Penalties" },
      { description: "Own Goals" },
      { description: "Expected Goals" },
      { description: "Non-penalty Expected Goals" },
      { description: "Non-penalty xG plus Expected Assisted Goals" },
      { description: "Non-penalty xG per Shot" },
      { description: "xG plus xAG" },
      { description: "xG Plus/Minus" },
      { description: "xG Plus/Minus per 90" },
      { description: "Non-penalty Goals minus xG" },
    ],
  },
  {
    name: "Assists & Creation",
    keys: [
      { description: "Assists" },
      { description: "Expected Assists" },
      { description: "Expected Assisted Goals" },
      { description: "Key Passes" },
      { description: "Shot Creating Actions" },
      { description: "SCA per 90" },
      { description: "Goal Creating Actions" },
      { description: "GCA per 90" },
    ],
  },
  {
    name: "Shooting",
    keys: [
      { description: "Shots" },
      { description: "Shots on Target" },
      { description: "Shots on Target Percentage" },
      { description: "Shots per 90" },
      { description: "Shots on Target per 90" },
      { description: "Average Shot Distance" },
    ],
  },
  {
    name: "Passing",
    keys: [
      { description: "Passes Completed" },
      { description: "Pass Completion Percentage" },
      { description: "Passes Attempted" },
      { description: "Live Ball Passes" },
      { description: "Dead Ball Passes" },
      { description: "Assists" },
      { description: "Through Balls" },
      { description: "Key Passes" },
      { description: "Passes into Penalty Area" },
      { description: "Crosses" },
      { description: "Crosses into Penalty Area" },
      { description: "Average Pass Distance" },
      { description: "Average Pass Length" },
      { description: "Long Ball Percentage" },
      { description: "Switches" },
      { description: "Throw-Ins" },
      { description: "Turnovers" },
      { description: "Dead Ball Passes" },
      { description: "Live Ball Passes" },
    ],
  },
  {
    name: "Dribbling & Carrying",
    keys: [
      { description: "Carries" },
      { description: "Progressive Carries" },
      { description: "Progressive Carry Distance" },
      { description: "Progressive Runs" },
      { description: "Miscontrols" },
      { description: "Dispossessed" },
      { description: "Dribbles Attempted" },
      { description: "Successful Dribbles" },
      { description: "Dribble Success Percentage" },
      { description: "Dribbles in Attacking Third" },
      { description: "Dribbles in Penalty Area" },
    ],
  },
  {
    name: "Defending",
    keys: [
      { description: "Tackles" },
      { description: "Tackles Won" },
      { description: "Tackles plus Interceptions" },
      { description: "Tackle Success Percentage" },
      { description: "Interceptions" },
      { description: "Blocks" },
      { description: "Clearances" },
      { description: "Errors" },
      { description: "Defensive Actions" },
      { description: "Defensive Third" },
      { description: "Defensive Penalty Area" },
      { description: "Possession Lost" },
      { description: "Duels Won" },
      { description: "Duels Won Percentage" },
      { description: "Fouls Drawn" },
      { description: "Fouls Committed" },
      { description: "Yellow Cards" },
      { description: "Red Cards" },
      { description: "Second Yellow Cards" },
      { description: "Penalties Won" },
      { description: "Penalties Conceded" },
    ],
  },
  {
    name: "Goalkeeping",
    keys: [
      { description: "Clean Sheets" },
      { description: "Clean Sheet Percentage" },
      { description: "Saves" },
      { description: "Save Percentage" },
      { description: "Goals Against" },
      { description: "Goals Against per 90" },
      { description: "Shots on Target Against" },
      { description: "Post-Shot Expected Goals" },
      { description: "PSxG per Shot on Target" },
      { description: "PSxG Plus/Minus" },
      { description: "Penalties Against" },
      { description: "Penalty Saves" },
      { description: "Penalty Attempts" },
      { description: "Penalty Misses" },
    ],
  },
  {
    name: "Other/Advanced",
    keys: [
      { description: "Competitions Played" },
      { description: "Subbed Out" },
      { description: "Subbed In" },
      { description: "Passes Received" },
      { description: "Recoveries" },
      { description: "Touches" },
      { description: "Total Distance" },
      { description: "On-field xG" },
      { description: "On-field xGA" },
      { description: "On-field Goals" },
      { description: "On-field Goals Against" },
      { description: "Plus/Minus" },
      { description: "Plus/Minus per 90" },
      { description: "Offensive Possession Added" },
      { description: "OPA per 90" },
      { description: "Per 90" },
      { description: "Defensive Actions" },
      { description: "Opponents" },
      { description: "Stops" },
      { description: "Stop Percentage" },
      { description: "Throws" },
      { description: "Free Kicks" },
      { description: "Corner Kicks" },
      { description: "Completed Passes Attempted" },
      { description: "Average Length" },
      { description: "Switches" },
      { description: "Throw-Ins" },
      { description: "Turnovers" },
      { description: "Live Ball" },
      { description: "Dead Ball" },
    ],
  },
];


export const categoryKeyMap: Record<string, Record<string, string | null>> = {
  Personal: {
    "Year of Birth": "Born",
    "Age": "Age",
    "Nationality": "Nation",
    "Team/Squad": "Squad",
    "Position": "Pos",
    "Competition": "Comp",
  },
  "Playing Time": {
    "Matches Played": "MP",
    "Minutes Played": "Min",
    "Percentage of Team Minutes Played": "Min%",
    "Games Started": "Starts",
    "Substitute Appearances": "Subs",
    "Minutes per Match": "Mn/MP",
    "Minutes per Start": "Mn/Start",
    "Minutes per Substitute Appearance": "Mn/Sub",
    "Unused Substitute": "unSub",
    "Times Substituted In": "In",
    "Times Substituted Out": "Out",
  },
  "Team Results": {
    "Wins": "W",
    "Losses": "L",
    "Team Goal Difference On/Off Pitch": "On-Off",
    "Points Per Match": "PPM",
  },
  "Goals & Scoring": {
    "Goals": "Gls",
    "Goals minus Penalties": "G-PK",
    "Goals minus Expected Goals": "G-xG",
    "Goals per Shot": "G/Sh",
    "Goals per Shot on Target": "G/SoT",
    "Goals plus Assists": "G+A",
    "Goals plus Assists minus Penalties": "G+A-PK",
    "Own Goals": "OG",
    "Expected Goals": "xG",
    "Non-penalty Expected Goals": "npxG",
    "Non-penalty xG plus Expected Assisted Goals": "npxG+xAG",
    "Non-penalty xG per Shot": "npxG/Sh",
    "xG plus xAG": "xG+xAG",
    "xG Plus/Minus": "xG+/-",
    "xG Plus/Minus per 90": "xG+/-90",
    "Non-penalty Goals minus xG": "np:G-xG",
  },
  "Assists & Creation": {
    "Assists": "Ast",
    "Expected Assists": "xA",
    "Expected Assisted Goals": "xAG",
    "Key Passes": "KP",
    "Shot Creating Actions": "SCA",
    "SCA per 90": "SCA90",
    "Goal Creating Actions": "GCA",
    "GCA per 90": "GCA90",
  },
  Shooting: {
    "Shots": "Sh",
    "Shots on Target": "SoT",
    "Shots on Target Percentage": "SoT%",
    "Shots per 90": "Sh/90",
    "Shots on Target per 90": "SoT/90",
  },
  Passing: {
    "Passes Completed": "Cmp",
    "Pass Completion Percentage": "Cmp%",
    "Passes Attempted": "Att",
    "Live Ball Passes": "PassLive",
    "Dead Ball Passes": "PassDead",
    "Through Balls": "TB",
    "Key Passes": "KP",
    "Passes into Penalty Area": "PPA",
    "Crosses": "Crs",
    "Crosses into Penalty Area": "CrsPA",
    "Switches": "Sw",
    "Turnovers": "TO",
  },
  "Dribbling & Carrying": {
    "Carries": "Carries",
    "Progressive Carries": "PrgC",
    "Progressive Carry Distance": "PrgDist",
    "Progressive Runs": "PrgR",
    "Miscontrols": "Mis",
    "Dispossessed": "Dis",
    "Dribbles Attempted": "Att",
    "Successful Dribbles": "Succ",
    "Dribble Success Percentage": "Succ%",
    "Dribbles in Attacking Third": "Att 3rd",
    "Dribbles in Penalty Area": "Att Pen",
  },
  Defending: {
    "Tackles": "Tkl",
    "Tackles Won": "TklW",
    "Tackles plus Interceptions": "Tkl+Int",
    "Tackle Success Percentage": "Tkl%",
    "Interceptions": "Int",
    "Blocks": "Blocks",
    "Clearances": "Clr",
    "Errors": "Err",
    "Defensive Actions": "Stp",
    "Defensive Third": "Def 3rd",
    "Defensive Penalty Area": "Def Pen",
    "Possession Lost": "Lost",
    "Duels Won": "Won",
    "Duels Won Percentage": "Won%",
    "Fouls Drawn": "Fld",
    "Fouls Committed": "Fls",
    "Yellow Cards": "CrdY",
    "Red Cards": "CrdR",
    "Second Yellow Cards": "2CrdY",
    "Penalties Won": "PKwon",
    "Penalties Conceded": "PKcon",
  },
  Goalkeeping: {
    "Clean Sheets": "CS",
    "Clean Sheet Percentage": "CS%",
    "Saves": "Saves",
    "Save Percentage": "Save%",
    "Goals Against": "GA",
    "Goals Against per 90": "GA90",
    "Shots on Target Against": "SoTA",
    "Post-Shot Expected Goals": "PSxG",
    "PSxG per Shot on Target": "PSxG/SoT",
    "PSxG Plus/Minus": "PSxG+/-",
    "Penalties Against": "PKA",
    "Penalty Saves": "PKsv",
    "Penalty Attempts": "PKatt",
    "Penalty Misses": "PKm",
    "Average Shot Distance": "AvgDist",
    "Average Punt Length": "AvgLen",
    "Long Ball Percentage": "Launch%",
  },
  "Other/Advanced": {
    "Competitions Played": null,
    "Subbed Out": "Out",
    "Subbed In": "In",
    "Passes Received": "Rec",
    "Recoveries": "Recov",
    "Touches": "Touches",
    "On-field xG": "onxG",
    "On-field xGA": "onxGA",
    "On-field Goals": "onG",
    "On-field Goals Against": "onGA",
    "Plus/Minus": "+/-",
    "Plus/Minus per 90": "+/-90",
    "Offensive Possession Added": "#OPA",
    "OPA per 90": "#OPA/90",
    "Per 90": "/90",
    "Defensive Actions": "Stp",
    "Opponents": "Opp",
    "Stops": "Stp",
    "Stop Percentage": "Stp%",
    "Throws": "Thr",
    "Free Kicks": "FK",
    "Corner Kicks": "CK",
    "Completed Passes Attempted": "Compl",
    "Throw-Ins": "TI",
    "Turnovers": "TO",
    "Live Ball": "Live",
    "Dead Ball": "Dead",
  },
};