export interface FifaPlayerProfile {
  Acceleration: number;
  Age: number;
  Aggression: number;
  Agility: number;
  "Alternative positions": string;
  Balance: number;
  "Ball Control": number;
  Composure: number;
  Crossing: number;
  Curve: number;
  DEF: number;
  DRI: number;
  "Def Awareness": number;
  Dribbling: number;
  Finishing: number;
  "Free Kick Accuracy": number;
  "GK Diving": string;
  "GK Handling": string;
  "GK Kicking": string;
  "GK Positioning": string;
  "GK Reflexes": string;
  "Heading Accuracy": number;
  Height: string;
  ID: string;
  Interceptions: number;
  Jumping: number;
  League: string;
  "Long Passing": number;
  "Long Shots": number;
  Name: string;
  Nation: string;
  OVR: number;
  PAC: number;
  PAS: number;
  PHY: number;
  Penalties: number;
  Position: string;
  Positioning: number;
  "Preferred foot": string;
  Rank: number;
  Reactions: number;
  SHO: number;
  "Short Passing": number;
  "Shot Power": number;
  "Skill moves": number;
  "Sliding Tackle": number;
  "Sprint Speed": number;
  Stamina: number;
  "Standing Tackle": number;
  Strength: number;
  Team: string;
  Vision: number;
  Volleys: number;
  "Weak foot": number;
  Weight: string;
  "play style": string;
  url: string;
}
